Algoritmo "AULA 06 - EXERCICIO 03 - CONVERSOR DE TEMPERATURA"

Var
// Seção de Declarações das variáveis 
   Fahrenheit ,  Celsius : REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

      ESCREVA ("QUAL A TEMPERATURA EM EUA? ")
      LEIA (Fahrenheit)
      
      Celsius <- (Fahrenheit - 32) / 1.8
      
      ESCREVA ("NO BRASIL ESTARIA COM A TEMPERATURA DE",Celsius,"°")
      
Fimalgoritmo