Algoritmo "AULA 06 - EXERCICIO 04 - IMPPOSTO DE 60% "

Var
// Seção de Declarações das variáveis 
     DOLAR , IMPOSTO , REAIS :REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    ESCREVA ("QUANTO VOCÊ COMPROU EM DOLAR DE MERCADORIA?")
    LEIA (DOLAR)
    
    IMPOSTO <- (DOLAR * 60) / 100
    REAIS <- IMPOSTO * 2.22
    ESCREVAL ("O IMPOSTO EM DORLAR USD:",IMPOSTO)
    ESCREVAL ("O IMPOSTO EM REAIS  R$:",REAIS)

    
    

Fimalgoritmo