Algoritmo "AULA 06 - EXERCICIO  01 - DATA DE ANIVERSARIO "

Var
// Seção de Declarações das variáveis 

   ANO_ATUAL,  ANO_NASC, IDADE : INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     ESCREVA ("EM QUAL ANO  ESTAMOS?")
     LEIA (ANO_ATUAL)
     ESCREVA ("EM QUE ANO VOCÊ NASCEU?")
     LEIA (ANO_NASC)
     
     IDADE <- ANO_ATUAL - ANO_NASC
     
     ESCREVA ("SUA IDADE É ",IDADE," ANOS")

Fimalgoritmo