Algoritmo "AULA 04 - EXPLICAÇÃO 01 - OPERADORES RELACIONAIS "

// OPERADORES RELACIONAIS
// > - MAIOR QUE
// < - MENOR QUQ
// >= - MAIOR OU IGUAL A
// <= - MENOR OU IGUAL A
// = IGUAL A
// <> - DIFERENTE DE


Var
//
     A , B , C :INTEIRO

Inicio
//
       A <- 2
       B <- 3
       C <- 5
       ESCREVAL (A >= B)
       ESCREVAL (A <= B)
       ESCREVAL (A > 2)
       ESCREVAL (C = A+B)
       ESCREVAL (C >= B^A)

Fimalgoritmo