Algoritmo "AULA 07 - EXPLICAÇÃO 01 - ESTRUTURA CONDICIONAL SE - PAR OU IMPAR"

Var
// Seção de Declarações das variáveis 

    N: INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA ("DIGITE UM NUMERO:")
   LEIA (N)

   SE (N % 2 = 0) ENTAO
      ESCREVAL ("O NUMERO ",N," É PAR.")
   SENAO
      ESCREVAl ("O NUMERO ",N," É IMPAR.")
   FIMSE
   

   


Fimalgoritmo
