Algoritmo "PASSO 07 - REPETIÇÃO COM PARA..ATE - EXERCICIO 67 - CONTA DE 0 ATE O NUMERO INFORMADO"


Var
   // Seção de Declarações das variáveis
    C1 ,NUMERO : INTEIRO

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

      ESCREVA ("DIGITE UM NUMERO:")
      LEIA (NUMERO)
      PARA C1 := 0  ATE  NUMERO PASSO 1 FACA
         ESCREVA (C1,",")
      FIMPARA

Fimalgoritmo
