Algoritmo "PASSO 01 - SEQUENCIA BASICA - EXERCICIO 15 - DIAS TRABALHADOS"

Var
// Seção de Declarações das variáveis
    DIA, DIARIA:INTEIRO
    SALARIO:REAL


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

    ESCREVA  ("QUANTOS DIAS TRABALHADOS?")
    LEIA (DIA)
    
    DIARIA <- 8 * 25
    SALARIO <- DIA * DIARIA
    
    ESCREVAL ("SEU SALÁRIO É  R$:",SALARIO)
Fimalgoritmo