Algoritmo "PASSO 05 - REPETIÇÃO ENQUANTO COM FLAG - EXERCICIO 56 - REPETIR ATE DIGITAR 1111"

Var
// Seção de Declarações das variáveis 

  NUMERO, SOMA, SOMA2: INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ENQUANTO (NUMERO <> 1111) FACA
   ESCREVA ("DIGITE UM NUMERO?")
   LEIA (NUMERO)
   SOMA <- SOMA + NUMERO
   FIMENQUANTO
   SOMA2 <- SOMA - 1111
   ESCREVA ("A SOMA DOS NUMEROS É", SOMA2)
Fimalgoritmo