Algoritmo "PASSO 01 - SEQUENCIA BASICA - EXERCICIO 10 - CALCULO DO DELTA"

Var
// Seção de Declarações das variáveis 

   A, B, C, DELTA: REAL
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     ESCREVA ("DIGITE O  VALOR DE A: ")
     LEIA (A)
     ESCREVA ("DIGITE O  VALOR DE B: ")
     LEIA (B)
     ESCREVA ("DIGITE O  VALOR DE C: ")
     LEIA (C)
     
     DELTA <- ((B ^ 2) - (4 * (A * C)))

     ESCREVA (DELTA)
Fimalgoritmo