Algoritmo "PASSO 01 - SEQUENCIA BASICA - EXERCICIO 05 - MEDIA DO ALUNO"

Var
// Seção de Declarações das variáveis 
    NOTA1, NOTA2, MEDIA: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      ESCREVA ("DIGITE A 1° NOTA: ")
      LEIA(NOTA1)
      ESCREVA ("DIGITE A 2° NOTA: ")
      LEIA (NOTA2)

      MEDIA <- (NOTA1 + NOTA2)/2

      ESCREVA("A MÉDIA DO ALUNO É ", MEDIA)

Fimalgoritmo