Algoritmo "PASSO 01 - SEQUENCIA BASICA - EXERCICIO 04 - SOMA DE DOIS NUMERO"

Var
// Seção de Declarações das variáveis 

    NUMERO1, NUMERO2 , SOMA : INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     ESCREVA ("DIGITE O 1° NUMERO: ")
     LEIA (NUMERO1)
     ESCREVA ("DIGITE O 2° NUMERO; ")
     LEIA (NUMERO2)
     
     SOMA <- NUMERO1 + NUMERO2
     
     ESCREVA ("A SOMA É ", SOMA)
Fimalgoritmo