Algoritmo "PASSO 01 - SEQUENCIA BASICA - EXERCICIO 07 - O DOBRO E A TERÇA PARTE DE UM NUMERO"

Var
// Seção de Declarações das variáveis 
   NUMERO , DOBRO, TERCAPARTE :REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   ESCREVA ("DIGITE UM NUMERO: ")
   LEIA (NUMERO)

   DOBRO <- 2 * NUMERO
   TERCAPARTE <- NUMERO / 3
   
   ESCREVAL ("O DOBRO DE ", NUMERO," É ", DOBRO)
   ESCREVAL ("A TERÇA PARTE DE ",NUMERO," É ", TERCAPARTE)
Fimalgoritmo