Algoritmo "PASSO 04 - REPETIÇÃO ENQUANTO    - EXERCICIO 42 - CONTAGEM ATE NUMERO DIGITADO"

Var
   // Seção de Declarações das variáveis
  NUMERO, CONTADOR :INTEIRO

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   ESCREVA ("DESEJA CONTAR ATÉ QUANTO?")
   LEIA (NUMERO)

   CONTADOR <-1

   ENQUANTO CONTADOR <= NUMERO FACA
      ESCREVA (CONTADOR)
      CONTADOR <- CONTADOR + 1
   FIMENQUANTO

Fimalgoritmo


