Algoritmo "PASSO 02 - CONDIÇÕES BÁSICAS - EXERCICIO 21 - PAR OU IMPAR "
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

// Seção de Declarações das variáveis 
VAR
   N: INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc.
   ESCREVA ("DIGITE UM NUMERO:")
   LEIA (N)
   ESCREVAL (N)
   SE (N % 2 = 0) ENTAO
      ESCREVA ("ESSE NUMERO É PAR")
   SENAO
        ESCREVA ("ESSE NUMERO É IMPAR")
   FIMSE
Fimalgoritmo
