algoritmo "PASSO 08 - VETORES - EXERCICIO 77 - LER 7 NOMES  "

var
Vet: vetor[1..7] de CARACTERE
C: inteiro
inicio

PARA C <- 1 ATE 7 FACA
ESCREVA ("INFORME SEU NOME:")
LEIA  (VET[C])
FIMPARA

LIMPATELA

escreval ("=================================")
escreval ("LISTAGEM DO NOMES NA ORDEM IVERSA")
escreval ("=================================")
para C <- 7 ate 1 passo -1 faca
   escreval (Vet[C])
Fimpara

fimalgoritmo





