Algoritmo "AULA 09 - EXPLICAÇÃO 02 - ESTRUTURA DE REPETIÇÃO ENQUANTO..FAÇA - CONTAR DE 5 A 0 "

Var
// Seção de Declarações das variáveis
   CONTADOR : INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   CONTADOR <- 5

   ENQUANTO (CONTADOR >= 0) FACA
            ESCREVAL (CONTADOR)
            CONTADOR <- CONTADOR - 1
   FIMENQUANTO

   ESCREVA ("TERMINEI DE CONTAR")

Fimalgoritmo