Algoritmo "AULA 09 - EXPLICAÇÃO 01 - ESTRUTURA DE REPETIÇÃO ENQUANTO..FAÇA - CONTAR DE 0 A 10 "

Var
// Seção de Declarações das variáveis 
   CONTADOR : INTEIRO
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   CONTADOR <- 0
   
   ENQUANTO (CONTADOR <= 5) FACA
            ESCREVAL (CONTADOR)
            CONTADOR <- CONTADOR + 1
   FIMENQUANTO

   ESCREVA ("TERMINEI DE CONTAR")

Fimalgoritmo