Algoritmo "AULA 15 - EXPLICAÇÃO 01  - MATRIZES - LER MATRIZ"


Var
   M: VETOR [1..3, 1..2]DE INTEIRO
   L,C: INTEIRO

Inicio

   PARA L <- 1 ATE 3 FAÇA
      PARA C <- 1 ATE 2 FACA
         ESCREVA ("DIGITE UM VALOR DA POSIÇÃO [", L," ,", C," ]: ")
         LEIA(M[L,C])
      FIMPARA
   FIMPARA

   PARA L <- 1 ATE 3 FACA
      PARA C <- 1 ATE 2 FACA
         ESCREVA(M[L,C]:5)
      FIMPARA
      ESCREVAL ()
   FIMPARA


Fimalgoritmo